name: A workflow for my Hello World file
on: pull_request
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          ifconfig
          ip addr list
      - uses: ./.github/actions/minikube
      - run: |
          echo "IPADDR=${IPADDR}"
