name: Respin images for a released tag
on: 
  push:
    # Sequence of patterns matched against tags
    # Right now, we run this job automatically when a semantically versioned
    # tag is pushed.
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: 'A version (git tag) that has already been released'
        required: true
jobs:
  build:
    name: Print respective tag
    runs-on: ubuntu-latest
    steps:
      - name: Identify version
        run: |
          if [ -z "${{github.event.inputs.tag}}" ]; then
            echo "CONTAINER_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          else
            #echo "${{github.event.inputs.tag}}" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+' || { echo "A valid tag is expected"; exit 1; }
            #export LAST_BUILD_NUMBER=$(curl -s https://quay.io/api/v1/repository/skupper/skupper-router/tag/?filter_tag_name=like:${{github.event.inputs.tag}} | jq .tags[].name | grep -E "\"${{github.event.inputs.tag}}-[0-9]+\"" | wc -l || echo 0)
            #[[ ${LAST_BUILD_NUMBER} -eq 0 ]] && { echo "No reference to tag ${{github.event.inputs.tag}} has been found"; exit 1; }
            echo "CONTAINER_TAG=${{github.event.inputs.tag}}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v2
        with:
          ref: ${CONTAINER_TAG}
#      - name: Verify a valid tag has been provided
#        run: |
          #echo "${CONTAINER_TAG}" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+' || { echo "A valid tag is expected"; exit 1; }
          #export LAST_BUILD_NUMBER=$(curl -s https://quay.io/api/v1/repository/skupper/skupper-router/tag/?filter_tag_name=like:${CONTAINER_TAG} | jq .tags[].name | grep -E "\"${CONTAINER_TAG}-[0-9]+\"" | wc -l || echo 0)
          #[[ ${LAST_BUILD_NUMBER} -eq 0 ]] && { echo "No reference to tag ${CONTAINER_TAG} has been found"; exit 1; }
          #echo "Valid tag provided: ${CONTAINER_TAG}"
      - name: Valid release provided
        run: |
          echo ${CONTAINER_TAG}
