name: Manually build and publish qdrouterd nightly image
on: workflow_dispatch
jobs:
  has-changes:
    name: Verify if qpid-dispatch has changed in the past 24h
    outputs:
      changed: ${{ steps.changed-24h.outputs.changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./.github/scripts/github-changed-24h.sh
        id: changed-24h
  build-nightly:
    name: Publish qdrouterd nightly image
    needs: has-changes
    if: ${{ needs.has-changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Changed: ${{needs.has-changes.outputs.changed}}"
          echo Build, test and publish nightly image
          echo "${NAME} - NAME is a secret defined on github"
        env:
          NAME: ${{ secrets.NAME }}
