name: Respin images for a released tag
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'A version (git tag) that has already been released'
        required: true
jobs:
  build:
    name: Print respective tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.tag}}
      - name: Get the tag name and set it as the CONTAINER_TAG env variable.
        run:  |
          echo "CONTAINER_TAG=${{github.event.inputs.tag}}" >> $GITHUB_ENV
      - name: Identify version
        run: |
          export PROJECT_TAG="${CONTAINER_TAG}"
          export VERSION="${CONTAINER_TAG}"
          export BUILD_NUMBER=$((`curl -s https://quay.io/api/v1/repository/skupper/skupper-router/tag/?filter_tag_name=like:${VERSION} | jq .tags[].name | grep -E "\"${VERSION}-[0-9]+\"" | wc -l || echo 0` + 1))
          # Only accepts tag if build_number is higher than one
          [[ ${BUILD_NUMBER} -eq 1 ]] && { echo "The provided tag (${VERSION}) does not refer to a released image. You must provide a tag that has already been released."; exit 1; }

          echo "CONTAINER_TAG=${{github.event.inputs.tag}}" >> $GITHUB_ENV
      - name: Valid release provided
        run: |
          echo ${CONTAINER_TAG}
