name: Sample workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Sample job
    runs-on: ubuntu-24.04
    steps:
      - name: Install latest docker
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          
          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          
          sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Build and publish images using docker buildx
        env:
          CONTAINER_USER: '${{ secrets.CONTAINER_USER }}'
          CONTAINER_PASSWORD: '${{ secrets.CONTAINER_PASSWORD }}'
        run: |
          wget https://gist.github.com/fgiorgetti/5991e9eb835f8e5acfee78ee6f969c2b/archive/6dd821628ddbc098d2e617247ae7ea8466a77905.zip
          unzip 6dd821628ddbc098d2e617247ae7ea8466a77905.zip
          cd 5991e9eb835f8e5acfee78ee6f969c2b-6dd821628ddbc098d2e617247ae7ea8466a77905
          echo "${CONTAINER_PASSWORD}" | docker login --username "${CONTAINER_USER}" --password-stdin quay.io
          docker buildx create --use
          bash ./build.sh

