name: Build and Publish qdrouterd image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Sample job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: ./ansible_collections/skupper/v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
          cache: 'pip'
      - name: Testing python dep
        run: |
          pip install kubernetes
          python --version
          python -c 'import kubernetes'
      - name: Build skupper-router
        uses: ./.github/actions/build-router
      - name: Minikube
        uses: ./.github/actions/minikube
      - name: Docker
        uses: ./.github/actions/docker
      - name: Podman
        uses: ./.github/actions/podman
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Create a lb service
        run: kubectl create service loadbalancer sample --tcp=8080
      - name: Check service ip
        run: |
          kubectl wait --for=jsonpath='{.status.loadBalancer.ingress}' service/sample
          kubectl get -o wide service/sample
