name: Trying podman on a vm
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Podman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt -y update
      - run: |
          sudo apt -y install podman
      - run: |
          podman version
