name: Podman system tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Podman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Disable selinux
        run: |
          sudo setenforce 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: ./.github/actions/podman-latest
      - uses: ./.github/actions/minikube-latest
      - name: Cloning skupper 
        run: |
          git clone -b podman https://github.com/fgiorgetti/skupper
      - name: Generating podman clients
        run: |
          cd skupper
          make generate-client
      - name: Skupper Podman System Tests
        run: |
          cd skupper
          # disabling selinux
          setenforce 0
          go test -count=1 -v -tags=podman ./pkg/domain/podman/... -use-cluster
