name: Trying podman on a fedora vm
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Podman on fedora
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt -y update
          sudo apt -y install podman
          podman version
