name: Podman system tests
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Podman
    runs-on: ubuntu-latest
    steps:
      - name: Install latest podman
        run: |
          sudo apt -y update
          sudo apt -y install podman
          podman version
#      - uses: actions/checkout@v2
#        with:
#          path: ./my-checkout-path
#          dir: ./my-checkout-path
#      - name: evaluating checkout
#        run: |
#          pwd
#          ls -l
#          find
#      - uses: actions/setup-go@v2
#        with:
#          go-version: '1.17'
#      - uses: ./.github/actions/podman-latest
#      - uses: ./.github/actions/minikube-latest
#      - name: Cloning skupper 
#        run: |
#          git clone https://github.com/skupperproject/skupper
#      - name: Generating podman clients
#        run: |
#          cd skupper
#          make generate-client
#      - name: Skupper Podman System Tests
#        run: |
#          #cd skupper && podman unshare go test -count=1 -v -tags=podman ./pkg/domain/podman/... -use-cluster
#          cd skupper && go test -count=1 -v -tags=podman ./pkg/domain/podman/... -use-cluster
