name: Build and Publish qdrouterd image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Publish qdrouterd image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo Merged to ${GITHUB_REF}
