name: Build and Publish qdrouterd image
on:
  push:
    branches:
      - master-disabled
jobs:
  build:
    name: Publish qdrouterd image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo Merged to ${GITHUB_REF}
          echo "${#NAME} - NAME is a secret defined on github as a repository secret"
        env:
          NAME: '${{ secrets.NAME }}'
