name: Release when version tag pushed
on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Print respective tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Identify version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          echo ${RELEASE_VERSION}
          export BUILD_NUMBER=$((`curl -s https://quay.io/api/v1/repository/skupper/skupper-router/tag/?filter_tag_name=like:${RELEASE_VERSION} | jq .tags[].name | grep -E "\"${RELEASE_VERSION}-[0-9]+\"" | wc -l || echo 0` + 1))
          ./.github/scripts/image.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - TBD
            - TBD
            - https://github.com/fgiorgetti/hello-github-actions/issues?q=is:issue%20milestone:${RELEASE_VERSION}
          draft: true
          prerelease: false
