name: Release when version tag pushed
on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build:
    name: Print respective tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Identify version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: |
          echo ${RELEASE_VERSION}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - TBD
            - TBD
          draft: true
          prerelease: false
